### PR TITLE
Commons fileupload headerfix

### PR DESCRIPTION
**Pull request by developerSid**
Added call that sets the parsed headers on the currentHeaderItem instances in FileUploadBase

### CODE REVIEW

**Comment by kinow** [comment]
Hmmm, this pull request seems to be a bit messed up due to either changes in the branch, or to the way the commit was created. There are also IDE files committed. @developerSid if you could update the pull request, making sure to rebase your changes against the remote branch, that might make it easier to be reviewed.

Thanks
Bruno

**Comment by developerSid** [comment]
Sure I can give that a try.  I had forgotten about having actually done this.

**Comment by jochenw** [comment]
Honestly: 88 files changed for one pull request? No chance to get that pulled in. Try to split your changes into smaller change sets.

**Comment by jochenw** [comment]
On another issue: Please remove .classpath, and .project from the pull request. These are IDE specific, thus not supposed to live in an Apache project.

**Comment by developerSid** [comment]
I totally agree this was a pretty botched pull request.  How would you like me to handle this once I get it fixed?  Leave this thread open and comment here with the new pull request?

**Comment by developerSid** [comment]
I just checked the code out, and this has already been fixed.  Looks like the change I wanted to try and get into upstream was done on 3/16/2011 by Wiedmann.  I'm going to close this.  Thanks for taking a look though guys.  I really appreciate it.

**Pull request closed without merging**
