### PR TITLE
FILEUPLOAD-324 - Use java9 profile on JDK 9 and later

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Review by jochenw — CHANGES_REQUESTED** [review]
Could you, please, add a reference for the trouble with Jacoco in Java 13? So, that there is something, that we can track and use as a source for the decision to revert.

**Comment by arturobernalg** [comment]
> Could you, please, add a reference for the trouble with Jacoco in Java 13? So, that there is something, that we can track and use as a source for the decision to revert.

Hi @jochenw 
since fileupload inherit from commons parent use the version 0.8.6 that support java 13 no need skip jacoco.
Remove the comment
TY

**Review by jochenw — CHANGES_REQUESTED** [review]
Okay, but another question: As we are inheriting from the parent, wouldn't it be wise to retain the profile id ("java9", rather than "java9+")?

**Comment by arturobernalg** [comment]
> Okay, but another question: As we are inheriting from the parent, wouldn't it be wise to retain the profile id ("java9", rather than "java9+")?

HI @jochenw 
Well, maybe you're right. Maybe I haven't thought it through. Rollback madeed
YY

**Comment by jochenw** [comment]
As far as I can tell, this is now reduced to introducing a new profile "java13", that is activated when building on Java 13, but not later.
Okay, but that profile is empty. So, what's the point?

**Comment by arturobernalg** [comment]
> As far as I can tell, this is now reduced to introducing a new profile "java13", that is activated when building on Java 13, but not later.
> Okay, but that profile is empty. So, what's the point?
Hi @jochenw . you are right, now seems logical close this PR

**Pull request closed without merging**
