### PR TITLE
improve GC by avoiding FileInput/Output-Streams

### PR DESCRIPTION
**Pull request by alexander-riss**
bump compiler target from 1.5 to 1.7

see:  https://bugs.openjdk.java.net/browse/JDK-8080225

### CODE REVIEW

**Comment by jochenw** [comment]
As far as I can tell, requiring 1.7 is still no option, because Fileupload is used in basically every application container, that I am aware of, and there are lots of them out in the wild, which are way below 1.7.  And, by reading the OpenJDK issue, I do not get the impression, that your issue is urgent.

**Comment by alexander-riss** [comment]
as java < 1.7 is no longer supported through oracle it would be the question how many of the app-servers which would integrate this version (as in: latest-version) still support java < 1.7

i agree that this is not a critical issue - but also an example of progress being held back by these legacy system. I guess a new mayor version branch for these kind of issues would be a solution?

**Comment by sebbASF** [comment]
Note that Oracle still offers (paid) support for versions of Java before 7:

http://www.oracle.com/technetwork/java/javase/eol-135779.html#java-commercial-offerings

**Comment by jvz** [comment]
I don't see Oracle passing along that money to the ASF to continue maintaining Java 6 software, though. ;)

**Comment by jochenw** [comment]
@jvz I don't see anyone passing along any money. This is true open source software. We're doing, what we consider to be best for our users in general.

@alexander-riss Please note, there's a workaround: By setting sizeThreshold sufficiently high on the DiskFileItemFactory, you prevent files being created at all.

**Comment by ecki** [comment]
Note that this might improve slightly the finalizer pressure however FileChannel(InputStreams) have pretty much internal overheads including locks and synchronized, so the actual performance might regress badly.

**Comment by jochenw** [comment]
@ecki  Given a reasonable value for sizeThreshold, I'd expect that only very few files are actually being created (say one per request, which is the actual uploaded file), so I wouldn't care too much about that. Which is, on the other hand, another reason, why this isue isn't overly pressing.

**Pull request closed without merging**
