### PR TITLE
javax.servlet.* to jakarta.servlet.* namespace transition

### PR DESCRIPTION
**Pull request by jGauravGupta**
Signed-off-by: Gaurav Gupta <gaurav.gupta.jc@gmail.com>

### CODE REVIEW

**Comment by rmannibucau** [comment]
Hi @jGauravGupta ,

Tihs looks like an invasive breaking change for end users so would require to upgrade the version to a new major + almost nobody migrated to jakarta namespace since it is not yet a thing.

What about the compromise picked by some other project to deliver another artifact where javax is replaced by jakarta but keep the primary artifact as a javax one.
You can do it just adding shade plugin, see this example for johnzon: https://github.com/apache/johnzon/blob/master/pom.xml#L99

Maybe a compromise to investigate which will enable jakarta usage without breaking all javax users.

**Comment by jGauravGupta** [comment]
Hi @rmannibucau,

This PR can be closed in favor of #26.

**Comment by jochenw** [comment]
Please check, whether commit cd031805d2618b0c1dd9c90265ebea1a1ce85387 isn't essentially, what you need. If so, please close this PR.

**Comment by jochenw** [comment]
@jGauravGupta As a housekeeping issue, please be so kind to close this PR.

**Comment by jGauravGupta** [comment]
Thanks @jochenw for adding the Jakarta Servlet support, I will check with Woodstock build and create the issue here, if needed.

**Pull request closed without merging**
