### PR TITLE
Adding Power Support

### PR DESCRIPTION
**Pull request by lysannef**
Adding support for travis job on ppc64le architecture.

### CODE REVIEW

**Comment by jochenw** [comment]
Please, look at the following in the PR: "The Travis CI build did not complete..."
Now, as this is about travis anyways, I'd like to see it fixed.

**Comment by lysannef** [comment]
@jochenw  The build has been failing at that [job](https://travis-ci.org/apache/commons-fileupload/jobs/562910828) (https://travis-ci.org/apache/commons-fileupload/builds) on previous builds as well.
It wasn't caused due to this PR.

**Comment by jochenw** [comment]
Yes, but as you seem to be concerned about Travis, and have more knowledge than me in that area: Perhaps you could fix it?

**Comment by aherbert** [comment]
The project source code is 1.8. JDK 1.7 should not be in the build matrix.

**Comment by aherbert** [comment]
@lysannef I've just fixed master with the change to drop JDK 1.7. Since the source code is 1.8 a switch to openjdk 1.7 will not work.

Can you rebase?

**Comment by lysannef** [comment]
@aherbert  Thanks !  Yes will rebase.

**Comment by lysannef** [comment]
@jochenw  All checks are now passing.
@aherbert  Thanks for your help.

**Comment by lysannef** [comment]
@jochenw  All checks passing. Can this be merged?

**Comment by lysannef** [comment]
@garydgregory Reverted the EOL change

**Pull request merged**
